apiVersion: v1
kind: Service
metadata:
  name: mlapps-service
spec:
  selector:
    app: mlapps
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2000
      nodePort: 30080
